### PR TITLE
SystemUI: add haptic feedback for qs tiles

### PR DESCRIPTION
**Pull request by Wahid7852**
Change-Id: Id2acde26c0c650ee8bd1482bdcce06a223143fbc

### CODE REVIEW

**Comment by ShevT** [comment]
@gwolf2u @neobuddy89 This works good!

**Comment by DeanWinchesterrr** [comment]
Yes !!!!! Please add this

**Comment by Saikrishna1504** [comment]
Qs haptics 😍😍

**Comment by P4RZIVAL286** [comment]
Major need 🫡🫡

**Comment by SHADOW-REX** [comment]
Much requested feature!

**Review by gwolf2u — APPROVED** [review]

**Pull request merged**
