### PR TITLE
base: Blacklist Realme{Parts,Dirac} for Parallel space

### PR DESCRIPTION
**Pull request by sarthakroy2002**
Change-Id: I1f3677fa1ead3f9f74bcc98427d7302184d9e0c1
Signed-off-by: Sarthak Roy <sarthakroy2002@gmail.com>

### CODE REVIEW

**Comment by neobuddy89** [comment]
@ShevT this  should go as array that devices can overlay in their device tree.

**Comment by sarthakroy2002** [comment]
> @ShevT this should go as array that devices can overlay in their device tree.

Which array overlay?

**Comment by gwolf2u** [comment]
> @ShevT this should go as array that devices can overlay in their device tree.

this is for sure the way
some would like to blacklist whoever knows what device specific app

**Comment by neobuddy89** [comment]
@sarthakroy2002 Use below config overlays in device tree.

https://github.com/crdroidandroid/android_frameworks_base/commit/f48b8b1d0a29e52edb3f2bbe7332d313c61a6cc9

**Pull request closed without merging**
