### PR TITLE
Add Mono audio tile (aka headphone in one ear only)

### PR DESCRIPTION
**Pull request by Mustang-ssc**
thanks buffal0b1ll for the suggestion!

Signed-off-by: Mustang-ssc <mustangssc@protonmail.ch>

### CODE REVIEW

**Comment by ghost** [comment]
Isn't the title wrong? It doesn't make audio in one ear only. It merges both audio channels & outputs single channel into both sides.

**Comment by Mustang-ssc** [comment]
> It merges both audio channels & outputs single channel into both sides.

That's actually what it does (tested). I am unaware of the meaning of the whole title, either way it switches between stereo/mono.

**Comment by xNombre** [comment]
I'm not a fan of this change. Sounds kinda useless. -1
Adding reviewers.

**Comment by neobuddy89** [comment]
I agree this is useless - cant understand message on TG that said "this is gift to community" lol.
Added for accessibility purpose for now.

**Pull request closed without merging**
