### PR TITLE
base: Add DC dimming support

### PR DESCRIPTION
**Pull request by uixdess**
* Update AppLock to v1.1

### CODE REVIEW

**Comment by neobuddy89** [comment]
sepolicy changes?

**Comment by Hikari-no-Tenshi** [comment]
AppLock needs changes in Settings.

**Comment by Hikari-no-Tenshi** [comment]
https://github.com/ResurrectionRemix/Resurrection_packages_apps_Settings/commit/bf56dc3a5539ad8b855ae3cf00e743868fa771a8

**Comment by neobuddy89** [comment]
@Hikari-no-Tenshi any way to link this with face unlock?

**Comment by Hikari-no-Tenshi** [comment]
> 
> 
> @Hikari-no-Tenshi any way to link this with face unlock?

Not sure. PA has different face unlock.

**Comment by neobuddy89** [comment]
Ok

**Comment by uixdess** [comment]
> sepolicy changes?

No need

> AppLock needs changes in Settings.

Yeah, I know, just forgot to push and create PR. 
https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/pull/663
https://github.com/crdroidandroid/android_packages_apps_Settings/pull/89

**Comment by Hikari-no-Tenshi** [comment]
> 
> 
> > sepolicy changes?
> 
> No need
> 
> > AppLock needs changes in Settings.
> 
> Yeah, I know, just forgot to push and create PR.
> [crdroidandroid/android_packages_apps_crDroidSettings#663](https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/pull/663)
> [crdroidandroid/android_packages_apps_Settings#89](https://github.com/crdroidandroid/android_packages_apps_Settings/pull/89)

You can set sepolicy in device tree but there is some base sepolicy for DC Dimming.
https://github.com/Hikari-no-Tenshi/android_device_crdroid_sepolicy/commit/d33f3ee1e72cb9d157e657db2f4af472ee34d094

**Comment by uixdess** [comment]
> > > sepolicy changes?
> > 
> > 
> > No need
> > > AppLock needs changes in Settings.
> > 
> > 
> > Yeah, I know, just forgot to push and create PR.
> > [crdroidandroid/android_packages_apps_crDroidSettings#663](https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/pull/663)
> > [crdroidandroid/android_packages_apps_Settings#89](https://github.com/crdroidandroid/android_packages_apps_Settings/pull/89)
> 
> You can set sepolicy in device tree but there is some base sepolicy for DC Dimming.
> [Hikari-no-Tenshi/android_device_crdroid_sepolicy@d33f3ee](https://github.com/Hikari-no-Tenshi/android_device_crdroid_sepolicy/commit/d33f3ee1e72cb9d157e657db2f4af472ee34d094)

Thanks. Added.
https://github.com/crdroidandroid/android_device_crdroid_sepolicy/pull/8

**Comment by Hikari-no-Tenshi** [comment]
@uixdess fix commit https://github.com/crdroidandroid/android_frameworks_base/commit/4a51c20ae11e0e67e301ab0ee0de96999422ba62
Delete code:
```
        /**
         * Indicates whether we should only show the app lock view when the device is woken up
         * Or always.
         * @hide
         */
        public static final String APP_LOCK_HIDE_NOTIFICATIONS = "app_lock_hide_notifications";
```

**Comment by Hikari-no-Tenshi** [comment]
It is fine with me to merge all of this pull requests.

**Comment by gwolf2u** [comment]
> 
> 
> It is fine with me to merge all of this pull requests.

feel free to do it 👍

**Pull request merged**
