### PR TITLE
Fix toast for RTL layout

### PR DESCRIPTION
**Pull request by zardav**
Fix bug: no text in toast when layout is RTL

### CODE REVIEW

**Comment by gwolf2u** [comment]
I am not really familiar with RTL formatting 
will this alter any LTR text?

**Comment by zardav** [comment]
It has no influence for LTR layout, as in LTR right=end, the difference is
in RTL.
The bug is probably cherry picked from cm 12.1 or something based on it.
You can see in cm 12.1 that this is the way they fixed this bug.
https://review.lineageos.org/#/c/67377/

>

**Comment by zardav** [comment]
I hope it is possible to apply the also it to 8.1 branch.

**Comment by neobuddy89** [comment]
Let me merge this in few min. Thanks.

**Pull request merged**
