### PR TITLE
Edge lightning

### PR DESCRIPTION
**Pull request by Laker87**

### CODE REVIEW

**Comment by Laker87** [comment]
Fixed Edge lighting not working for notifications with hidden sensitive content

**Comment by neobuddy89** [comment]
Shouldn't this be squashed in single commit?

@gwolf2u

**Comment by gwolf2u** [comment]
Agree

**Comment by gwolf2u** [comment]
@Laker87 please squash (git rebase -i HEAD~23) all those commits into one
would be easier for us merge this and easy tracking
would also be nice to do it before next security patch merge

**Comment by Laker87** [comment]
> @Laker87 please squash (git rebase -i HEAD~23) all those commits into one
> would be easier for us merge this and easy tracking
> would also be nice to do it before next security patch merge

Ok

**Comment by Laker87** [comment]
Done

**Pull request closed without merging**
