### PR TITLE
Add lockscreen background blur

### PR DESCRIPTION
**Pull request by Laker87**

### CODE REVIEW

**Comment by neobuddy89** [comment]
This should be added with toggle in crdroid settings.

**Comment by Laker87** [comment]
> This should be added with toggle in crdroid settings.

is not blur toggle in display settings enough?

**Comment by neobuddy89** [comment]
it will disable blur everywhere and restart would be required.
user may prefer to keep wallpaper completely visible and have blur at other places.

**Comment by Laker87** [comment]
> it will disable blur everywhere and restart would be required.
> user may prefer to keep wallpaper completely visible and have blur at other places.

Ok

**Pull request closed without merging**
