### PR TITLE
SystemUI: Don't shift KeyguardSecurityContainer when FOD isn't available

### PR DESCRIPTION
**Pull request by Laker87**
Tests:
    -removed enrolled fp, ensured keyguardsecuritycontainer wasn't shifed
    -removed enrolled fp, rebooted, ensured keyguardsecuritycontainer (on SIM PIN) wasn't shifted

Change-Id: Iccf469fa4fed79ff0edde014ba165eef6ee024e1

### CODE REVIEW

**Comment by Hikari-no-Tenshi** [comment]
I'm still on cr6 and not sure about this change, but isn't this breaking commit https://github.com/crdroidandroid/android_frameworks_base/commit/f31f5848f516cf93d7163ce80d4cecb158ea1925 ?

**Comment by Laker87** [comment]
> 
> 
> I'm still on cr6 and not sure about this change, but isn't this breaking commit [f31f584](https://github.com/crdroidandroid/android_frameworks_base/commit/f31f5848f516cf93d7163ce80d4cecb158ea1925) ?

Without this commit FOD overpalps 0 key of keyguard, FOD is hidden at that moment but still active.

**Comment by gwolf2u** [comment]
this actually reverts https://github.com/crdroidandroid/android_frameworks_base/commit/f31f5848f516cf93d7163ce80d4cecb158ea1925
also I have no such issues with FOD and "0" overlapping
maybe adjust keyguard_indication_margin_bottom_fingerprint_in_display ?

Screenshot_20210131-161422

**Comment by Laker87** [comment]
> this actually reverts [f31f584](https://github.com/crdroidandroid/android_frameworks_base/commit/f31f5848f516cf93d7163ce80d4cecb158ea1925)
> also I have no such issues with FOD and "0" overlapping
> maybe adjust keyguard_indication_margin_bottom_fingerprint_in_display ?
> 
> Screenshot_20210131-161422

Does keyguard not shifted for you after reboot when you have to enter pin or pattern? Because minBottomMargin=0 in this case sinse !mUpdateMonitor.userNeedsStrongAuth().

**Comment by gwolf2u** [comment]
yes keyguard does move on userNeedsStrongAuth but doesn't interact with 0 button
why FOD is active when not in use?

**Comment by Laker87** [comment]
> yes keyguard does move on userNeedsStrongAuth but doesn't interact with 0 button
> why FOD is active when not in use?

It is the issue with xiaomi fingerprint blob, it always listens FOD key even if FOD is not active which leads to problem with swipe to recents gesture stuck,  problem with keyboard in bubbles and others. But we solved that problem using keyhandler and this commit is not necessary anymore for davinci, but maybe other devices have same problem.

**Pull request merged**
