### PR TITLE
FODAnimation

### PR DESCRIPTION
**Pull request by Hikari-no-Tenshi**

### CODE REVIEW

**Comment by gwolf2u** [comment]
testing and seems alright in WIP branch
tried to optimize png files (60MB), yet not much improvement (only recovered like less then 1MB)

**Comment by neobuddy89** [comment]
60MB where?

**Comment by gwolf2u** [comment]
fod animations
Basically png files (taken from OEM stock ROMS)

**Comment by neobuddy89** [comment]
where are they located? do they get added for all?

**Comment by gwolf2u** [comment]
In this commit https://github.com/crdroidandroid/android_frameworks_base/commit/c22c87345415b0a1f9ab7babb0272f8bf3e79ead
Ideas to lower?

**Comment by Hikari-no-Tenshi** [comment]
Real effect will be with lossy compress.

**Comment by gwolf2u** [comment]
Yeah tried lossless

**Comment by Hikari-no-Tenshi** [comment]
https://pngquant.org/

**Comment by neobuddy89** [comment]
Remove 
"BatteryMeterView: fix logcat warning spam "

Proper fix added.

**Comment by gwolf2u** [comment]
merged

**Pull request closed without merging**
