### PR TITLE
sensors block

### PR DESCRIPTION
**Pull request by Hikari-no-Tenshi**

### CODE REVIEW

**Review by neobuddy89 — COMMENTED** [review]
Iterating list THRICE. Bad code practice.

**Comment by Hikari-no-Tenshi** [comment]
@neobuddy89 what do you think about this https://github.com/Hikari-no-Tenshi/crdroid_android_frameworks_base/commit/ceb262fd2700a4bd2fedf8c325e2127384f9cffd

**Comment by neobuddy89** [comment]
Added.
CHeck this https://github.com/crdroidandroid/android_frameworks_base/commit/260002dbc3e2d61cef5a54bea661309f03075fba

**Comment by neobuddy89** [comment]
@Hikari-no-Tenshi I believe packages should be configurable like how we have in Gaming Mode.

**Comment by Hikari-no-Tenshi** [comment]
> 
> 
> @Hikari-no-Tenshi I believe packages should be configurable like how we have in Gaming Mode.

Was thinking about that, but with my skills this will take some time to implement.

**Pull request closed without merging**
