### PR TITLE
Make seekbar sexy

### PR DESCRIPTION
**Pull request by adi153**

### CODE REVIEW

**Comment by gwolf2u** [comment]
care to share some screens
not sure we actually need this

**Comment by adi153** [comment]
> care to share some screens
> not sure we actually need this

Already shared sir check dev group

**Comment by gwolf2u** [comment]
Please share here so others can decide also
Didn't see dev chat post

**Comment by adi153** [comment]
Screenshot_20200420-201556
Screenshot_20200420-201352
Screenshot_20200420-201313
Screenshot_20200420-201323
Screenshot_20200420-201304

**Comment by sysxda** [comment]
Looks awesome

**Comment by Advertpavan** [comment]
Noice.

**Comment by Hikari-no-Tenshi** [comment]
For my taste seek circle looks little ugly.

**Comment by anisnoorudheen** [comment]
Nice and looking good 👍😎

**Comment by Anush02198** [comment]
Looks Good :)

**Comment by Mustang-ssc** [comment]
Would prefer it to be an alternative alongside the stock one, so you can choose which to take IMO.

**Comment by officialyash007** [comment]
Looks good

**Comment by raystef66** [comment]
> Would prefer it to be an alternative alongside the stock one, so you can choose which to take IMO.

+1

**Comment by gwolf2u** [comment]
this can be done dt side if actually needed
https://github.com/crdroidandroid/android_frameworks_base/pull/410/commits/21f5650ea49891664d493a913889d5e7aff9fe9b

**Comment by officialyash007** [comment]
> Would prefer it to be an alternative alongside the stock one, so you can choose which to take IMO.

+1

**Comment by Hikari-no-Tenshi** [comment]
79765269-03069800-8344-11ea-9c60-88c4009ce173

1. Will look better with reduced height of seekbar.
2. Will look better without rectangle around circle.

**Comment by raystef66** [comment]
> this can be done dt side if actually needed
> [21f5650](https://github.com/crdroidandroid/android_frameworks_base/commit/21f5650ea49891664d493a913889d5e7aff9fe9b)

could line thickness and slider dot be made customisable in crdroid settings?

**Comment by jomadeto** [comment]
> Would prefer it to be an alternative alongside the stock one, so you can choose which to take IMO.

Same opinion

**Comment by uixdess** [comment]
I think not really good variant. There are some better options from other ROMs. What do you think about such implementation?
IMG_20200420_192317_349

**Comment by neobuddy89** [comment]
Need some mechanism to switch this on since it kills AOSP design completely.

**Pull request closed without merging**
