### PR TITLE
Auto brightness fix for oneplus 7 series

### PR DESCRIPTION
**Pull request by mukesh22584**

### CODE REVIEW

**Review by neobuddy89 — CHANGES_REQUESTED** [review]
config_brightnessRampRateSlowFloat not defined.

**Comment by mukesh22584** [comment]
> config_brightnessRampRateSlowFloat not defined.

Isn't it device specific overlay ?

**Comment by neobuddy89** [comment]
How do you overlay it if it's not present in source?

Moreover, the code compilation will fail since you are looking for the undefined symbol in source whether or not defined in device tree .

**Comment by mukesh22584** [comment]
> How do you overlay it if it's not present in source?
> 
> Moreover, the code compilation will fail since you are looking for the undefined symbol in source whether or not defined in device tree .

Ahh ! My bad, I've missed commits.

**Comment by neobuddy89** [comment]
Added.

**Pull request closed without merging**
