### PR TITLE
PR1

### PR DESCRIPTION
**Pull request by ShevT**

### CODE REVIEW

**Comment by neobuddy89** [comment]
Remove
[iorap: Enable by default](https://github.com/crdroidandroid/android_frameworks_base/pull/821/commits/6b51afceaf147d3f8412094a0ad5b9da4c6ed8f1)
[6b51afc](https://github.com/crdroidandroid/android_frameworks_base/pull/821/commits/6b51afceaf147d3f8412094a0ad5b9da4c6ed8f1)

[fwb: Keyguard: reduce bottom text size](https://github.com/crdroidandroid/android_frameworks_base/pull/821/commits/19a9a711b2627aadf6320867e0607cb2f53adb70)

[fwb: AOD: Sleep when proximity is covered for 3 secs](https://github.com/crdroidandroid/android_frameworks_base/pull/821/commits/2b59f73fd816589c8ceea13b5c8ffa57c932642b)

**Comment by neobuddy89** [comment]
Remove 
[base: Remove keyguard delay completely](https://github.com/crdroidandroid/android_frameworks_base/pull/821/commits/f73b336fbd94a1741cda4858e916abce3c741c59)

**Comment by neobuddy89** [comment]
Add this with toggle with default to aosp design of center QS page dots

[fwb: SystemUI: Show daily data usage in QS footer](https://github.com/crdroidandroid/android_frameworks_base/pull/821/commits/cf6278017eb2283639a33295f76bf97a0501b527)

**Comment by neobuddy89** [comment]
Abandoned
[SystemUI: AuthController: Fix ripple animation for side fp devices](https://github.com/crdroidandroid/android_frameworks_base/pull/821/commits/14e1da5e32369da5b31f0e4c29c32fd2bec13109)

https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/326693

**Comment by ShevT** [comment]
Why not added [fwb: SystemUI: Clear all button styles](https://github.com/crdroidandroid/android_frameworks_base/pull/821/commits/82f96c2219e97042cfedc00314dedcc100875d69)?

**Comment by neobuddy89** [comment]
> Why not added [fwb: SystemUI: Clear all button styles](https://github.com/crdroidandroid/android_frameworks_base/pull/821/commits/82f96c2219e97042cfedc00314dedcc100875d69)?

Bad code quality, unnecessary imports, buttons don't change on ui mode toggle, too many bad design icons.

**Pull request closed without merging**
