### PR TITLE
Fix lockscreen carrier text padding

### PR DESCRIPTION
**Pull request by HELLBOY017**

### CODE REVIEW

**Comment by gwolf2u** [comment]
please provide a screenshot

**Comment by HELLBOY017** [comment]
Screenshot_20210222-195030

@gwolf2u Before it was going under the punchhole but now it's perfect after applying this fix (Device:- OnePlus 8)

**Comment by gwolf2u** [comment]
this can be done dt side
wouldn't want to add this for all devices as some using un-curved display will look bad
ref: https://github.com/crdroidandroid/android_frameworks_base/blob/11.0/packages/SystemUI/res/values/dimens.xml#L786#L787

**Comment by HELLBOY017** [comment]
Well this is also buggy in kebab (goes under punchhole) and kebab's having flat display

**Comment by gwolf2u** [comment]
tried to add modification dt side?

**Comment by neobuddy89** [comment]
https://github.com/crdroidandroid/android_device_xiaomi_sm6150-common/commit/b2a564b62837c5e7affb21f4f1e6e835616789b5

**Comment by HELLBOY017** [comment]
Yes didn't fix 🥲

**Pull request closed without merging**
