### PR TITLE
base: Add Q style to battery icon

### PR DESCRIPTION
**Pull request by sukrut-kelkar**

### CODE REVIEW

**Comment by neobuddy89** [comment]
why is there havoc_config.xml ?
also does this affect AOSP portrait battery mode? i see code changes for it.

**Comment by sukrut-kelkar** [comment]
> why is there havoc_config.xml ?
> also does this affect AOSP portrait battery mode? i see code changes for it.

Actually i renamed havoc to cr so there's no havoc.xml
and nps every battery style working perfectly

**Comment by neobuddy89** [comment]
Pls submit as single commit. Helps to review better.

**Comment by gwolf2u** [comment]
This https://github.com/crdroidandroid/android_frameworks_base/commit/93229e2eec4f1d5da10004ab582b9205bf0588de and this https://github.com/crdroidandroid/android_frameworks_base/commit/99f408432abfc6eb5f841d2b659929b5e0c0d13c should be a single commit
Rest good for me

**Comment by sukrut-kelkar** [comment]
Ok

**Comment by neobuddy89** [comment]
All should be in one commit pls.

**Comment by gwolf2u** [comment]
> All should be in one commit pls.

Then why not squash those commits?

**Review by gwolf2u — APPROVED** [review]

**Pull request closed without merging**
