### PR TITLE
Alert slider

### PR DESCRIPTION
**Pull request by ShevT**
Works great on my OnePlus 7T Pro (hotdog)

### CODE REVIEW

**Comment by firebird11** [comment]
check these commits again, some files don't exist anymore

**Comment by ShevT** [comment]
> check these commits again, some files don't exist anymore

Checked. Everything compiled and works fine. 
What is your problem?

**Comment by firebird11** [comment]
[packages/SystemUI/src/com/android/systemui/tristate/TriStateUiControllerImpl.java]
this file ?

**Comment by firebird11** [comment]
i missed a file my bad , sorry

**Comment by ShevT** [comment]
This patches be accepted or not?

**Comment by gwolf2u** [comment]
Will review this week

**Comment by gwolf2u** [comment]
added

**Pull request closed without merging**
