### PR TITLE
Adding new header images

### PR DESCRIPTION
**Pull request by abdul-hubbali**
Added 4 new QS header images

### CODE REVIEW

**Comment by gwolf2u** [comment]
screenshots?

**Comment by abdul-hubbali** [comment]
I don't have screenshots, however these images have been made with the same resolution which is used in existing header images

**Comment by abdul-hubbali** [comment]
wp5385322-dragon-ball-pc-wallpapers-picsay
I have added those type of header images

**Comment by ShevT** [comment]
Looks really bad

Now:
Screenshot_20230502-095048_Настройки

This commit:
Screenshot_20230502-095214_Настройки

Screenshot_20230502-095221_Настройки

Screenshot_20230502-095225_Настройки

The brightness control has gone somewhere.

**Comment by abdul-hubbali** [comment]
I had just added images, haven't made any code changes

**Comment by neobuddy89** [comment]
Look at other pictures.
Pictures should go transparent near bottom end.

**Comment by abdul-hubbali** [comment]
Let me check

**Comment by ShevT** [comment]
And, please remove the last picture - crdroid. She is completely out of place and everything merges.

**Comment by abdul-hubbali** [comment]
I have changed overall transparency to 60%. Might work now.

**Comment by ShevT** [comment]
Now the size of the pictures is unrealistically huge
+760% ... 1100%

**Comment by abdul-hubbali** [comment]
its 2490*1040 resolution

**Comment by neobuddy89** [comment]
add more transparency in bottom, compress and send request again.

**Pull request closed without merging**
