### PR TITLE
FODCircleView: Fix high brightness after unlocking

### PR DESCRIPTION
**Pull request by gwolf2u**
all good

tested with dt reverts
https://github.com/crdroidandroid/android_device_oneplus_sm8150-common/commit/e6eb8d74d2fada278ee91cee1c0043973bfae74b
as well as kernel
https://github.com/crdroidandroid/android_kernel_oneplus_sm8150/commit/5d30560b3ae94fd9428cbde694faece7d40d8cf5

### CODE REVIEW

**Comment by gwolf2u** [comment]
@Hikari-no-Tenshi care to have a go?

**Comment by sysxda** [comment]
+1 fine for Xiaomi pyxis

**Comment by Hikari-no-Tenshi** [comment]
@gwolf2u did you tested dt reverts with enabled DC Dimming or enabled HBM mode?
Without this changes i had flashes of light (with DC Dimming) or wrong dim amount (with HBM mode).

**Comment by gwolf2u** [comment]
> @gwolf2u did you tested dt reverts with enabled DC Dimming or enabled HBM mode?
> Without this changes i had flashes of light (with DC Dimming) or wrong dim amount (with HBM mode).

using DC dimming
make sure to revert _drm/msm: keep dim_layer and HBM more in sync_
https://github.com/crdroidandroid/android_kernel_oneplus_sm8150/commit/5d30560b3ae94fd9428cbde694faece7d40d8cf5

**Comment by Hikari-no-Tenshi** [comment]
I don't have "drm/msm: keep dim_layer and HBM more in sync" in my kernel.

Reverted device tree commits, reverted "drm: msm: Add separate sysfs node for FOD dimming alpha" in kernel.

Flashes of light is back, so i will stick to my current implementation.

**Comment by gwolf2u** [comment]
> I don't have "drm/msm: keep dim_layer and HBM more in sync" in my kernel.
> 
> Reverted device tree commits, reverted "drm: msm: Add separate sysfs node for FOD dimming alpha" in kernel.
> 
> Flashes of light is back, so i will stick to my current implementation.

Can you check if there is any regression with this added and your implementation ?

**Comment by Hikari-no-Tenshi** [comment]
For more clean results will try with your kernel.

**Comment by Hikari-no-Tenshi** [comment]
Same issue with your kernel.
When DC Dimming enabled kernel calculates wrong dim value.

**Comment by Hikari-no-Tenshi** [comment]
Seems nothing broken with my current hal and kernel.

**Comment by gwolf2u** [comment]
think we can merge nonetheless ?
got better results here with this but willing to drop and keep current methods if causes issues with others

**Comment by Hikari-no-Tenshi** [comment]
> 
> 
> think we can merge nonetheless ?
> got better results here with this but willing to drop and keep current methods if causes issues with others

Nothing is broken for me.
If others OK then can be merged.

**Pull request merged**
