### PR TITLE
Allow APK signature scheme v1 for API 30+ apps

### PR DESCRIPTION
**Pull request by menorziin**

### CODE REVIEW

**Comment by gwolf2u** [comment]
What's the use case here?

**Comment by menorziin** [comment]
> What's the use case here?

It is necessary for manufacturer's camera on moto devices (tested in liber with and without commit)

**Comment by menorziin** [comment]
Without this the camera is not visible in the system

**Comment by gwolf2u** [comment]
Then suggest to create overlay for it as am no fan of having this for all devices

**Comment by menorziin** [comment]
> Then suggest to create overlay for it as am no fan of having this for all devices

Can you suggest me how to create this overlay?

**Pull request closed without merging**
