### PR TITLE
base: Double tap to trigger doze [1/2]

### PR DESCRIPTION
**Pull request by Laker87**
Thanks to yank555-lu for the original commit YAOSP-NG/frameworks_base@d6ac164.
Cleaned up and ported to Android 10 by SKULSHADY.

Change-Id: I4154925a0c7de37f1dc84b58b280691cc44d14c9
Signed-off-by: DennySPB <dennyspb@gmail.com>
Signed-off-by: Joey Huab <joey@evolution-x.org>

### CODE REVIEW

**Review by neobuddy89 — CHANGES_REQUESTED** [review]
1. DOZE_TRIGGER_DOUBLETAP is not defined in Settings.
2. When enabled, will this affect other wake keys too? Like pressing power button will doze the screen?

**Comment by Laker87** [comment]
> 
> 
>     1. DOZE_TRIGGER_DOUBLETAP is not defined in Settings.
> 
>     2. When enabled, will this affect other wake keys too? Like pressing power button will doze the screen?

1. Hm, it works without defining it in Settings.
2. No. Pressing the power button takes you directly to the lock screen.

**Comment by MASTERGUY** [comment]
about this are we going to add this if yes @Laker87 i suggest update it :)
thanks

**Review by gwolf2u — CHANGES_REQUESTED** [review]
rebase needed

**Comment by Laker87** [comment]
> rebase needed

Done

**Review by neobuddy89 — COMMENTED** [review]
Hold this for now. While it may work, implementation is incorrect.  
KEYCODE_WAKEUP -> is not only for double tap but for any wakeup key (like HW key?)
This shouldn't be messed with.

**Pull request closed without merging**
