### PR TITLE
Revert "Revert "DO NOT MERGE Revert "Adding the privacy chip to the C…

### PR DESCRIPTION
**Pull request by Hikari-no-Tenshi**
…arStatusBar"""

This reverts commit 3e49612528be481dfbd8a5fcb6ca5c9b80d1d478.

### CODE REVIEW

**Comment by Hikari-no-Tenshi** [comment]
Don't know how critical is this commit, but reverting it should fix Android Auto for now.

**Comment by gwolf2u** [comment]
does this work in emulator or in car system?
what was your testing environment?

**Comment by Hikari-no-Tenshi** [comment]
Tested in emulator, can't test in real car.
Phone not freezed and emulator started with map and my location and other controls.

**Comment by gwolf2u** [comment]
gonna test tomorrow

**Pull request merged**
