### PR TITLE
Revert "SystemUI: Clean up redundancy in BurnInProtection"

### PR DESCRIPTION
**Pull request by Terminator-J**
This reverts commit 83196305b9f1b5241c09abb64faf205230d34831.

Turns out we needed the extra passes through the view inflator in order to actually test whether burn-in protection had gone past the outer edge padding limits and horizontal/vertical shift limits or not.

This revert change keeps status bar items from wandering off under the corner or notch cutout padding boundaries, and having the battery icon get halfway cut off even though it's not actually at the edge of the screen yet.
_____

The h/v shift limits in question are Lineage-specific dimens in frameworks/base/packages/SystemUI/res/values/lineage_dimens.xml, so you'd overlay in overlay-lineage/frameworks/base/packages/SystemUI/res/values/dimens.xml if you want to change them to have a little more active burn-in protection.
Default values:
<dimen name="burnin_protection_horizontal_shift">3dp</dimen>
<dimen name="burnin_protection_vertical_shift">1dp</dimen>

The other ones with min & max horizontal/vertical shift & radius are, I believe, only applicable to the AOD dream when dozing.

### CODE REVIEW

**Comment by awakened1712** [comment]
We need to overlay this for the status bar
```
<dimen name="burnin_protection_horizontal_shift">1dp</dimen>
```

**Comment by Terminator-J** [comment]
> We need to overlay this for the status bar
> 
> ```
> <dimen name="burnin_protection_horizontal_shift">1dp</dimen>
> ```
Yes, you're right, that's one of them.
I forgot to add the markdown to escape the actual dimen resources in my original post; whoops. 😅 
Default values:
```
<dimen name="burnin_protection_horizontal_shift">3dp</dimen>
<dimen name="burnin_protection_vertical_shift">1dp</dimen>
```
That takes care of statusbar & navbar item burn-in protection shifting, so if we want more extreme (or less, or no vertical), then change device-tree overlays.

My understanding is that the following values only affected AOD doze dream (possibly lockscreen as well?):
```
<integer name="config_burnInProtectionMaxRadius">-1</integer>
<integer name="config_burnInProtectionMinHorizontalOffset">0</integer>
<integer name="config_burnInProtectionMaxHorizontalOffset">0</integer>
<integer name="config_burnInProtectionMinVerticalOffset">0</integer>
<integer name="config_burnInProtectionMaxVerticalOffset">0</integer>
```
(default values from frameworks/base/core/res/res/values/config.xml)
...but since the things in the middle of the screen can move around far more pixels without being immediately notable as "off-center", while things in statusbar fighting around a large central notch & large-radius round edges can't always move as far.
That's why I'm in favor of keeping two diffferent sets of overlays for burn-in protection like in upstream LineageOS. If we want the AOD things to shift more, we can just change the device tree overlays for just that portion.
Was it broken before somehow? Seemed to work to me...

**Comment by Terminator-J** [comment]
spacingB
With just this one revert commit applied, horizontal shift increased to 3.5dp, and vertical shift increased to 1.5dp, here's a composite screenshot (sorry the colors are off; was using "screen" blending mode in photoshop to make it easier to see all the statusbar "ghosts") with five different screenshots taken between 2:30 and 2:55PM this afternoon (with the screen kept on).

It already works, it's just subtle and takes a few minutes to ramp up.

**Comment by awakened1712** [comment]
Just change the update interval in BurnInProtectionController.java into 1 second, so that you can test easily.

The clean up was good to me. Status bar moves perfectly fine after reducing horizontal shift to 1 to make it not moving too far 
```
<dimen name="burnin_protection_horizontal_shift">1dp</dimen>
```

See video https://drive.google.com/file/d/1V48U82uyuBnXinHeNxK8RYcvdwzJ3Txo/view

**Comment by Terminator-J** [comment]
> Just change the update interval in BurnInProtectionController.java into 1 second, so that you can test easily.
> 
> Status bar moves perfectly fine to me after reducing horizontal shift to 1 to make it not moving too far
> 
> ```
> <dimen name="burnin_protection_horizontal_shift">1dp</dimen>
> ```
> 
> See video https://drive.google.com/file/d/1V48U82uyuBnXinHeNxK8RYcvdwzJ3Txo/view

I was already playing Vampire Survivors so the screen was on anyway. 😁 
But I'm *not* trying to make it shift less, I just want it to respect the limits in those overlays.

If we don't revert the commit, it doesn't respect the limits from that dimen resource **at all** and will run away out past the visible bounds of the layout, because it's a nested view. You end up with things like these:
- The battery and the clock are cut off even though they're not at the edge of the screens, due to using rounded_corner_content_padding dimen:
photo_2023-01-28_19-54-32

- It no longer switches to "overflow" dot, and just keeps pushing items in toward center until it gets cut off by "how far we can go into the notch area" dimen:
photo_2023-01-28_19-51-47

**Comment by awakened1712** [comment]
It does respect the defined horizontal and vertical shifts. The cut was because 3dp as default value on the screen is enormous. Changing horizontal shift to 1dp makes it move in a more acceptable range.

What is the problem of adjusting the horizontal shift?

**Comment by Terminator-J** [comment]
> It does respect the defined horizontal and vertical shifts. The cut was because 3dp as default value on the screen is enormous. Changing horizontal shift to 1dp makes it move in a more acceptable range.
> 
> What is the problem of adjusting the horizontal shift?

OH okay, I assumed it was (still?) part of LineageOS since it was a change in lineage_dimens.xml instead of cr_dimens.xml. You're right; it's not part of upstream Lineage.
_Regardless..._ with this un-reverted, it flies all over the place, not only "3dp".
With it reverted, 3dp actually means 3dp. If the optimization needs to be fixed and a scaling factor inserted, great; let's do that & fix up the commit then.
But as it is, with the original commit in place that tries to optimize the code path, 3dp does not equal 3dp. With it reverted, statusbar/navbar burn-in protection moves the specified amount and not further; so as far as I'm concerned it should be reverted.
Changing a resource value that's supposed to be in a certain type of unit because the math is wrong elsewhere (i.e. "make it 1dp instead so it only moves 10dp instead of 300dp") isn't a fix; fixing the math is a fix. Does that make sense; why I wouldn't want to just change my device tree overlay and walk away?

**Pull request closed without merging**
