### PR TITLE
Add "Kill app back button" [1/3]

### PR DESCRIPTION
**Pull request by faxor01**
Co-authored-by: Faxor
Co-authored-by: LineageOS

### CODE REVIEW

**Review by gwolf2u — CHANGES_REQUESTED** [review]
Please correct author

**Comment by faxor01** [comment]
Co-authored-by: Faxor
Co-authored-by: LineageOS

**Comment by faxor01** [comment]
Done

**Comment by neobuddy89** [comment]
--- do not merge ---
This will conflict with long press actions

**Comment by faxor01** [comment]
> --- do not merge ---
> This will conflict with long press actions

It doesn't, tested it myself

**Comment by neobuddy89** [comment]
what are you checking hardware key or navbar back key?

**Comment by faxor01** [comment]
Both

**Comment by neobuddy89** [comment]
Use "Back button long press" option under "Buttons" or "Stock Navbar Settings" to assign kill action.
https://github.com/crdroidandroid/android_frameworks_base/commit/8d2936a499113d2bcfcc632767e9fddf421bce0e
https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/commit/0dfbc8e79e4181a6834428d13e8ca6b26aa907c6

**Pull request closed without merging**
