### PR TITLE
Add FOD system overlay types

### PR DESCRIPTION
**Pull request by Hikari-no-Tenshi**

### CODE REVIEW

**Comment by neobuddy89** [comment]
Description why is this commit required?

**Comment by Hikari-no-Tenshi** [comment]
1. Add FOD system overlay types:
Needed to make FOD work when on screen displayed other layers that may cover it. FOD will work even with enabled Smart pixels.

2. FODCircleView: Add ability to dim FOD icon
Needed to fix very bright FOD icon when device have always enabled FOD high brightness mode.

Looks like second commit currently not needed. Will remove it.

**Comment by gwolf2u** [comment]
care to test if FOD with screen off works properly?

**Comment by gwolf2u** [comment]
@Hikari-no-Tenshi this still needed?
if yes, please force-push and will check

**Pull request merged**
