### PR TITLE
Changed Captive Portal URL From Google To GrapheneOS

### PR DESCRIPTION
**Pull request by ghost**
For a truely vanilla experience one needs to be free from google servers !
Though you don't use gapps google knows very well where you are !
You can verify
`curl -I http://connectivitycheck.grapheneos.network/generate_204`
`curl -I http://connectivitycheck.gstatic.com/generate_204`

### CODE REVIEW

**Comment by thestinger** [comment]
The GrapheneOS server is intended for use on GrapheneOS, not elsewhere.

**Comment by thestinger** [comment]
The GrapheneOS connectivity check server is only meant to be used on GrapheneOS.

**Comment by ghost** [comment]
> The GrapheneOS connectivity check server is only meant to be used on GrapheneOS.

What about http://captiveportal.kuketz.de ?

HTTP/1.1 204 No Content
Server: nginx
Date: Tue, 29 Dec 2020 02:02:59 GMT
Connection: keep-alive
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: DENY
Referrer-Policy: same-origin
Permissions-Policy: camera =(), microphone=()
Expect-CT: enforce, max-age=21600
Expect-Staple: max-age=31536000; includeSubdomains; preload
Content-Security-Policy: default-src 'none'

**Comment by thestinger** [comment]
You'll need to ask them.

**Comment by ghost** [comment]
> You'll need to ask them.

Like taking permission from google before releasing or even building a personal custom ROM
LOL :smile:

**Comment by thestinger** [comment]
AOSP is an open source project.

I strongly recommend having permission before deploying services as the preconfigured default in an OS.

GrapheneOS servers like grapheneos.network are infrastructure funded with donations to GrapheneOS. We don't have the resources to host services for use elsewhere.

**Comment by ghost** [comment]
> AOSP is an open source project.
> 
> I strongly recommend having permission before deploying services as the preconfigured default in an OS.
> 
> GrapheneOS servers like grapheneos.network are infrastructure funded with donations to GrapheneOS. We don't have the resources to host services for use elsewhere.

Open source project with closed sourced servers LMAO :smile:

**Comment by ghost** [comment]
You should go and fight all the people who changed their captive portal servers :smile: :smile: :smile: 
https://forum.xda-developers.com/t/guide-how-to-avoid-the-captive-portal-checkin-to-google.3927561/

**Comment by thestinger** [comment]
> Open source project with closed sourced servers LMAO

You seem quite confused. The servers are not closed source.

https://grapheneos.org/features#services
https://github.com/GrapheneOS/grapheneos.network

That doesn't mean it's okay to deploy our infrastructure as a preconfigured default in another projects without permission.

> You should go and fight all the people who changed their captive portal servers

You seem to be seriously misunderstanding what I'm talking about.

**Comment by gwolf2u** [comment]
this is not getting implemented
will get revised at a later time if there is a need for it (with our server)

**Pull request closed without merging**
