### PR TITLE
Spoof locked bootloader on hardware attestations

### PR DESCRIPTION
**Pull request by ghost**
Devices with broken TEE won't support this 😢 (will try to fix)

This will generate a valid certificate chain and pass Strong.

### CODE REVIEW

**Comment by Numaphor** [comment]
♥️

**Comment by raystef66** [comment]
Works fine on cepheus and alioth.

**Comment by gwolf2u** [comment]
not sure we want to use those certs 
also what's the reason to pass strong?

**Comment by rashadgasimli** [comment]
> not sure we want to use those certs also what's the reason to pass strong?

some bank, vpn, authenticator etc. apps require strong integrity.

**Comment by ghost** [comment]
> what's the reason to pass strong?

Some apps check in their servers the certificate chain, so including this will bypass those apps like WhatsApp.

Also, few apps are migrating to Strong integrity check, like Ingress (a game) and other bank and goverment apps.

**Comment by neobuddy89** [comment]
Merged. https://github.com/crdroidandroid/android_frameworks_base/commit/a932fb9b0490449eb82c55a305ccc878308d2ad7

**Review by nosu3380 — APPROVED** [review]

**Pull request closed without merging**
