### PR TITLE
Restore one-click to add/remove tiles after r19 merge

### PR DESCRIPTION
**Pull request by MASTERGUY**
Google now added the possibility to double click to move tiles
for accessibility purposes but i actually prefer the oneclick way

Change-Id: Ia44fc4e2ddc77c9cf918c2b8fea38a4e9a3c8252

### CODE REVIEW

**Comment by gwolf2u** [comment]
please rebase @MASTERGUY

**Comment by MASTERGUY** [comment]
> please rebase @MASTERGUY

do we really want to merge this or not i guess it is better to confirm it else i will close 🤔

**Comment by gwolf2u** [comment]
I'm ok with it either way
@crdroidandroid/maintainers ?

**Comment by DarkJoker360** [comment]
I think it is better to make another pr on top of the new code.

**Pull request closed without merging**
