### PR TITLE
SettingLib: Add deep sleep info to uptime preference

### PR DESCRIPTION
**Pull request by Razziell**
Add deep sleep ratio to "About Phone" -> "Uptime"
original from Stefan

### CODE REVIEW

**Comment by Razziell** [comment]
photo_2020-05-31_17-09-23
photo_2020-05-31_17-09-29

**Comment by neobuddy89** [comment]
Think this should go in battery info?

**Comment by gwolf2u** [comment]
Yeah, below the temp

**Comment by Razziell** [comment]
It is not necessary there. The redesigned battery does not look very aesthetically pleasing.
Corrected:
photo_2020-05-31_18-10-43
in cr:
photo_2020-05-31_18-10-51

> Think this should go in battery info?

**Comment by neobuddy89** [comment]
Above temp, below screen on.

**Pull request closed without merging**
