### PR TITLE
HeadsUp: add timeout option (1/2) and other...

### PR DESCRIPTION
**Pull request by ShevT**

### CODE REVIEW

**Comment by neobuddy89** [comment]
@ShevT pls code VPN provider below SmartPixels

    private final Provider<VpnTile> mVpnTileProvider;
    private final Provider<SmartPixelsTile> mSmartPixelsTileProvider;

**Comment by ShevT** [comment]
> pls code VPN provider below SmartPixels

@[neobuddy89](https://github.com/neobuddy89) Done

**Comment by neobuddy89** [comment]
https://github.com/crdroidandroid/android_frameworks_base/commit/cf0efe780eb30692d70df71a7780799e35c427a3

why is this commit repeated?

**Comment by neobuddy89** [comment]
iorap enabled in vendor
https://github.com/crdroidandroid/android_vendor_crdroid/blob/9dade041057f384c9932632aa043b0c724384149/config/crdroid.mk#L26

**Comment by ShevT** [comment]
> why is this commit repeated?


Hmm, yes, there is already such a test. But, they are falling apart.
We need to decide which one to keep.

**Comment by ShevT** [comment]
> iorap enabled in vendor https://github.com/crdroidandroid/android_vendor_crdroid/blob/9dade041057f384c9932632aa043b0c724384149/config/crdroid.mk#L26


I don't see any contradictions. My patch enable this by default. So you can throw out the extra line from the vendor.

**Comment by ShevT** [comment]
> [cf0efe7](https://github.com/crdroidandroid/android_frameworks_base/commit/cf0efe780eb30692d70df71a7780799e35c427a3)
> 
> why is this commit repeated?

threw away

**Comment by neobuddy89** [comment]
SystemUI: AuthController: Fix NPE due to isPowerbuttonFps() 

doesnt make sense.

**Comment by ShevT** [comment]
> SystemUI: AuthController: Fix NPE due to isPowerbuttonFps()
> 
> doesnt make sense.

removed

**Comment by gwolf2u** [comment]
please rebase this one and add only needed commits

**Pull request closed without merging**
