### PR TITLE
Props

### PR DESCRIPTION
**Pull request by Hikari-no-Tenshi**

### CODE REVIEW

**Comment by neobuddy89** [comment]
Why is Privileged App List prop being changed?

**Comment by Hikari-no-Tenshi** [comment]
> 
> 
> Why is Privileged App List prop being changed?

This props created for different purposes. Also props have limit in length. I think it's better to stick to default state.

**Comment by neobuddy89** [comment]
We have devices using vendor.camera.aux.packagelist, so better keep as it is.

**Comment by neobuddy89** [comment]
Perhaps, let me check more.

**Pull request merged**
