### PR TITLE
SystemUI: Show screenshot menu buttons without delay.

### PR DESCRIPTION
**Pull request by Laker87**
Also compress image a little bit.

### CODE REVIEW

**Comment by neobuddy89** [comment]
Compressing should be optional i guess.
We can provide tunable in settings - user can select from 10-100.
if 100 (default), no compressing.

**Comment by Laker87** [comment]
> Compressing should be optional i guess.
> We can provide tunable in settings - user can select from 10-100.
> if 100 (default), no compressing.

Good idea. Where is this option should be? CrDroidSettings?

**Comment by Laker87** [comment]
Removed image compression

**Review by neobuddy89 — COMMENTED** [review]
What's use of shareChip.intent?
Also, I am not sure of changes made in ScreenshotActionChip.java

**Comment by Laker87** [comment]
> What's use of shareChip.intent?

Wdym? It's used to share screenshots.

**Comment by Laker87** [comment]
> Also, I am not sure of changes made in ScreenshotActionChip.java

I thought to use synchronized threads, but method I used also works fine.

**Comment by neobuddy89** [comment]
> shareChip.intent

These are defined but not used.

        shareChip.intent = mImageData.shareAction.actionIntent;
        editChip.intent = mImageData.editAction.actionIntent;
        deleteChip.intent = mImageData.deleteAction.actionIntent;
        scrollChip.intent = mImageData.scrollAction.actionIntent;

**Comment by Laker87** [comment]
> > shareChip.intent
> 
> These are defined but not used.
> 
> ```
>     shareChip.intent = mImageData.shareAction.actionIntent;
>     editChip.intent = mImageData.editAction.actionIntent;
>     deleteChip.intent = mImageData.deleteAction.actionIntent;
>     scrollChip.intent = mImageData.scrollAction.actionIntent;
> ```

It's used in ScreenshotActionChip.java

**Comment by xNombre** [comment]
> 
> 
> > Compressing should be optional i guess.
> > We can provide tunable in settings - user can select from 10-100.
> > if 100 (default), no compressing.
> 
> Good idea. Where is this option should be? CrDroidSettings?

I don't like this idea. Such option would likely be useless, users don't care as long as their screenshots look good and detailed.
I would set compression to const 90-95% ratio. It's imperceptible and could lead to small size saving.

**Comment by neobuddy89** [comment]
Not required anymore.

**Pull request closed without merging**
