### PR TITLE
SystemUI: add more FOD icons [1/2]

### PR DESCRIPTION
**Pull request by Laker87**

### CODE REVIEW

**Comment by gwolf2u** [comment]
please rebase

**Review by gwolf2u — CHANGES_REQUESTED** [review]
please rebase

**Comment by Laker87** [comment]
> please rebase

Done

**Comment by gwolf2u** [comment]
added https://github.com/crdroidandroid/android_frameworks_base/commit/9e26ee8d8b0d824740b7b3ae54b17a026824f497

**Pull request closed without merging**
