### PR TITLE
ActiveServices: [FGS] Add exceptions for Google apps in foreground se…

### PR DESCRIPTION
**Pull request by afterallafk**
…rvice type validation

- Added a whitelist to bypass foreground service type validation for critical Google apps.
- Included packages such as com.google.android.gms, com.android.vending, and others.
- Ensures smooth operation of essential services like Google Play Services and Play Store.
- Logs bypass events for better debugging and monitoring.

### CODE REVIEW

**Comment by gwolf2u** [comment]
what's the exact use case for this?

**Comment by afterallafk** [comment]
> what's the exact use case for this?

For crashing google apps in some cases where the android system put the foreground service restriction due to which some apps crash or on the other hand some apps were not able to be installed from playstore.

**Comment by ossilator** [comment]
i think it would be prudent to explain why this somewhat ugly hard-coded centralized whitelist is the best/only option. it seems somewhat surprising to me that google didn't address this more elegantly.

**Comment by gwolf2u** [comment]
the whitelist should be done via xml source side
in fact (if I recall) even gapps package has it

**Comment by afterallafk** [comment]
> the whitelist should be done via xml source side in fact (if I recall) even gapps package has it

This method should also work I guess because if we see Pixelpropsutils there are also some names referenced in this format. So , technically it should also work.

**Comment by gwolf2u** [comment]
while it works, is just hardcoding some apps
not sure I like the approach
PPU is different use case

**Comment by afterallafk** [comment]
> while it works, is just hardcoding some apps not sure I like the approach PPU is different use case

Okay if you don't like this way we can use xml method then if it's okay for you.

**Pull request closed without merging**
