### PR TITLE
More features. Updated...

### PR DESCRIPTION
**Pull request by ShevT**

### CODE REVIEW

**Review by neobuddy89 — COMMENTED** [review]
I dont think  SettingsProvider: Allow WRITE_DEVICE_CONFIG 
fixes anything.

It's actually SettingsProvider complaining some other app not having this permission and trying to make some changes.

**Comment by ShevT** [comment]
> I dont think SettingsProvider: Allow WRITE_DEVICE_CONFIG fixes anything.
> 
> It's actually SettingsProvider complaining some other app not having this permission and trying to make some changes.

This problem has been known for a long time. It comes from GApps, but it is not solved. In my experience, this patch fixes it.
A source - https://review.lineageos.org/c/LineageOS/android_packages_apps_Settings/+/310806

**Comment by neobuddy89** [comment]
So, it's gapps with missing WRITE_DEVICE_CONFIG permission and not SettingsProvider?

**Comment by ShevT** [comment]
See the discussion I linked above.
You may not accept this patch. I will use it locally.

**Pull request closed without merging**
