### PR TITLE
SystemUI: Allow disabling fingerprint unlock animation

### PR DESCRIPTION
**Pull request by henricaodopao1**
This animation is causing lags on some devices with low specs, which annoys users everytime they unlock their phone.
Add a bool to disable it via overlay if needed.

co-authored-by: MLZ94 <zugutoroberto@gmail.com>

### CODE REVIEW

**Review by neobuddy89 — COMMENTED** [review]
Does this even compile?

**Comment by henricaodopao1** [comment]
sure

**Comment by neobuddy89** [comment]
Why not stop entire ripple effect?
/**
 * Expanding ripple effect
 * - startUnlockedRipple for the transition from biometric authentication success to showing
 * launcher.
 * - startDwellRipple for the ripple expansion out when the user has their finger down on the UDFPS
 * sensor area
 * - retractRipple for the ripple animation inwards to signal a failure
 */

**Comment by henricaodopao1** [comment]
its not necessary since the entire animation already gets disabled if we only disable startUnlockedRipple

**Comment by MLZ94** [comment]
> 

It's mainly startUnlockedRipple that causes the lag. Others animation are shorter and on a smaller part of the screen and no lag is noticable.

**Comment by MLZ94** [comment]
Also, udfps devices are less likely to be low end

**Comment by gwolf2u** [comment]
rebase?

**Pull request closed without merging**
