### PR TITLE
PR7

### PR DESCRIPTION
**Pull request by ShevT**

### CODE REVIEW

**Comment by neobuddy89** [comment]
frameworks/base: Provide required permission for cellbroadcastreceiver 

First add to app itself before adding to priv-app whitelist list.

**Comment by neobuddy89** [comment]
core: Wipe package cache on upgrade even on user build

is not required since we have 
https://github.com/crdroidandroid/android_frameworks_base/commit/c29066ecbea874b4db0b82e3648b514d2992631b

**Comment by neobuddy89** [comment]
base: limit direct share targets to reduce lag

No lag on direct share. If your device has lag, do create overlayable config.

**Comment by ShevT** [comment]
Package installer: show current and new version on apk installation - ???

**Comment by neobuddy89** [comment]
package installer commit -

will need to figure out strings - it should be moved to core/res/res/cr_strings.xml

for translations.

**Pull request closed without merging**
