### PR TITLE
more features

### PR DESCRIPTION
**Pull request by ShevT**

### CODE REVIEW

**Comment by ShevT** [comment]
Screenshots:
https://i.postimg.cc/T2LfQHjG/Screenshot-20220212-234917-Settings.png
https://i.postimg.cc/mkFXM9Hf/Screenshot-20220212-234944-Settings.png
https://i.postimg.cc/NLqNx06y/Screenshot-20220212-234957-Settings.png
https://i.postimg.cc/65Cwx21m/Screenshot-20220212-235014-Settings.png
https://i.postimg.cc/Mpxw66CK/Screenshot-20220212-235030-Settings.png
https://i.postimg.cc/HxNvVzj9/Screenshot-20220212-235112-Settings.png
https://i.postimg.cc/tRKyctD6/Screenshot-20220212-235138-Settings.png

**Comment by ShevT** [comment]
Is it time to add this already?

**Comment by gwolf2u** [comment]
source is focused on cr7 updates for now... this is added for review soon

**Comment by ShevT** [comment]
Ok

**Comment by neobuddy89** [comment]
What's purpose of Legacy WFD?

**Comment by ShevT** [comment]
> What's purpose of Legacy WFD?

See https://github.com/crdroidandroid/android_frameworks_av/pull/13
https://github.com/crdroidandroid/android_packages_apps_Settings/pull/112

**Comment by neobuddy89** [comment]
WFD Settings added 
https://github.com/crdroidandroid/android_packages_apps_Settings/commit/09576c06e69b6e2c9809ec4498e90e2055b5983f
https://github.com/crdroidandroid/android_device_crdroid_sepolicy/commit/d4a1763db7c4fac51dc9da869c629a79597ccec7

No need to change stuff in fwb.

**Comment by ShevT** [comment]
What about: "Wi-Fi timeout feature" and "Bluetooth timeout feature"?

**Comment by neobuddy89** [comment]
Reviewing. Will be added shortly

**Pull request closed without merging**
