### PR TITLE
Source additions

### PR DESCRIPTION
**Pull request by adiatul16**

### CODE REVIEW

**Comment by xNombre** [comment]
Lgtm. Can we drop Proton change for subsequent cumulative merge of its features? I dont like mixed merges

**Comment by neobuddy89** [comment]
Deep sleep preference need to be with its own preferencecontroller... not to be adjusted in existing.

**Comment by neobuddy89** [comment]
USAP pool can be enabled by prop in Device Tree, right?

persist.device_config.runtime_native.usap_pool_enabled=true

**Comment by neobuddy89** [comment]
Animation timings not to be tweaked - had long discussion earlier.

**Comment by neobuddy89** [comment]
Some commits should not be merged. Will pick required ones manually.

**Pull request closed without merging**
